config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  post 'newsletters/:id/send_newsletter', to: 'newsletters#send_newsletter', as: :newsletters_send_email

  resources :newsletters

  resources :subcribers

  root "newsletters#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

	connects_to database: { writing: :primary2, reading: :primary2}

	belongs_to :newsletter
	belongs_to :subcriber
end

app/models/newsletter.rb
class Newsletter < ApplicationRecord

	connects_to database: { writing: :primary, reading: :primary_replica}

	has_rich_text :content

	has_many :comments
end

app/models/subcriber.rb
class Subcriber < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
	
  def index
    @newsletters = Newsletter.all
  end
 
  def show
    @newsletter = Newsletter.find(params[:id])
  end
 
  def new
    @newsletter = Newsletter.new
  end
 
  def edit
    @newsletter = Newsletter.find(params[:id])
  end
 
  def create
    @newsletter = Newsletter.new(newsletter_params)
 
    if @newsletter.save
      redirect_to @newsletter
    else
      render 'new'
    end
  end
 
  def update
    @newsletter = Newsletter.find(params[:id])
 
    if @newsletter.update(newsletter_params)
      redirect_to @newsletter
    else
      render 'edit'
    end
  end
 
  def destroy
    @newsletter = Newsletter.find(params[:id])
    @newsletter.destroy
 
    redirect_to newsletters_path
  end

  def send_newsletter
    @newsletter = Newsletter.find(params[:id])
    Subcriber.all.each do |user|
      NewsletterMailer.newsletter_email(user, @newsletter).deliver_now
    end

    redirect_to newsletters_path
  end
 
  private
    def newsletter_params
      params.require(:newsletter).permit(:subject, :from_address, :content)
    end

end

app/controllers/subcribers_controller.rb
class SubcribersController < ApplicationController
	def index
    @subcribers = Subcriber.all
  end
 
  def show
    @subcriber = Subcriber.find(params[:id])
  end
 
  def new
    @subcriber = Subcriber.new
  end
 
  def edit
    @subcriber = Subcriber.find(params[:id])
  end
 
  def create
    @subcriber = Subcriber.new(subcriber_params)
 
    if @subcriber.save
      redirect_to @subcriber
    else
      render 'new'
    end
  end
 
  def update
    @subcriber = Subcriber.find(params[:id])
 
    if @subcriber.update(subcriber_params)
      redirect_to @subcriber
    else
      render 'edit'
    end
  end
 
  def destroy
    @subcriber = Subcriber.find(params[:id])
    @subcriber.destroy
 
    redirect_to subcribers_path
  end
 
  private
    def subcriber_params
      params.require(:subcriber).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/helpers/subcribers_helper.rb
module SubcribersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails6Implementation</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/newsletters/_form.html.erb
<%= form_for @newsletter, html:{multipart: true } do |f| %>
 
  <% if @newsletter.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@newsletter.errors.count, "error") %> prohibited
        this newsletter from being saved:
      </h2>
      <ul>
        <% @newsletter.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </p>
  
  <p>
    <%= f.label :from_address %><br>
    <%= f.text_field :from_address %>
  </p>

  <p>
    <%= f.label :content %><br>
    <%= f.rich_text_area :content %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/newsletters/edit.html.erb
<h1>Editing newsletter</h1>

<%= render 'form' %>

<%= link_to 'Show', @newsletter %> |
<%= link_to 'Back', newsletters_path %>

app/views/newsletters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing newsletters</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>From Address</th>
      <th colspan="3"></th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @newsletters.each do |newsletter| %>
    <div class="newsletter_wrapper">
      <tr>
        <td><%= newsletter.subject %></td>
        <td><%= newsletter.from_address %></td>
        <td><%= link_to 'Show', newsletter %></td>
        <td><%= link_to 'Edit', edit_newsletter_path(newsletter) %></td>
        <td><%= link_to 'Destroy', newsletter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'send_newsletter', newsletters_send_email_path(newsletter), method: :post, data: {confirm: 'It will send email to every one'} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New newsletter', new_newsletter_path %>

app/views/newsletters/new.html.erb
<h1>New newsletter</h1>

<%= render 'form' %>

<%= link_to 'Back', newsletters_path %>

app/views/newsletters/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @newsletter.subject %>
</p>

<p class="date">
   submitted <%= time_ago_in_words(@newsletter.created_at) %> Ago
</p>

<p>
  <strong>content:</strong>
  <%= @newsletter.content %>
</p>


 
<%= link_to 'Edit', edit_newsletter_path(@newsletter) %> |
<%= link_to 'Back', newsletters_path %>

<p>
  <strong>comments:</strong>
</p>
<p>
  <% @newsletter.comments.each do |msg| %>
  <p>
  	<strong><%= msg.subcriber.email %>:</strong>

  	<%= msg.body %>
  </p>
  <% end %>
</p>

app/views/subcribers/_form.html.erb
<%= form_for @subcriber, html:{multipart: true } do |f| %>
 
  <% if @subcriber.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@subcriber.errors.count, "error") %> prohibited
        this subcriber from being saved:
      </h2>
      <ul>
        <% @subcriber.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  
  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/subcribers/edit.html.erb
<h1>Editing subcriber</h1>

<%= render 'form' %>

<%= link_to 'Show', @subcriber %> |
<%= link_to 'Back', subcribers_path %>

app/views/subcribers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing subcribers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subcribers.each do |subcriber| %>
    <div class="subcriber_wrapper">
      <tr>
        <td><%= subcriber.name %></td>
        <td><%= subcriber.email %></td>
        <td><%= link_to 'Show', subcriber %></td>
        <td><%= link_to 'Edit', edit_subcriber_path(subcriber) %></td>
        <td><%= link_to 'Destroy', subcriber, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New subcriber', new_subcriber_path %>

app/views/subcribers/new.html.erb
<h1>New subcriber</h1>

<%= render 'form' %>

<%= link_to 'Back', subcribers_path %>

app/views/subcribers/show.html.erb
<p>
  <strong>name:</strong>
  <%= @subcriber.name %>
</p>

<p>
  <strong>email:</strong>
  <%= @subcriber.email %>
</p>
 
<%= link_to 'Edit', edit_subcriber_path(@subcriber) %> |
<%= link_to 'Back', subcribers_path %>